// Domenii de email de unică folosință — blocate la înscriere, ca aceeași persoană
// să nu poată lua trial-uri repetate cu adrese aruncabile. Listă intenționat
// scurtă (cele mai folosite servicii); extinde-o când apar altele noi.
const DOMENII_TEMPORARE = new Set([
  "mailinator.com",
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "sharklasers.com",
  "grr.la",
  "10minutemail.com",
  "10minutemail.net",
  "temp-mail.org",
  "tempmail.com",
  "tempmail.net",
  "temp-mail.io",
  "tempail.com",
  "tempmailo.com",
  "throwawaymail.com",
  "yopmail.com",
  "yopmail.net",
  "yopmail.fr",
  "trashmail.com",
  "trashmail.net",
  "trashmail.de",
  "getnada.com",
  "nada.email",
  "maildrop.cc",
  "dispostable.com",
  "fakeinbox.com",
  "mintemail.com",
  "mohmal.com",
  "emailondeck.com",
  "mytemp.email",
  "burnermail.io",
  "spamgourmet.com",
  "mailnesia.com",
  "moakt.com",
  "discard.email",
  "inboxkitten.com",
  "mail.tm",
  "tmpmail.org",
  "tmpmail.net",
  "dropmail.me",
  "emailfake.com",
  "fakemail.net",
  "jetable.org",
  "linshiyouxiang.net",
  "luxusmail.org",
  "armyspy.com",
  "cuvox.de",
  "dayrep.com",
  "einrot.com",
  "fleckens.hu",
  "gustr.com",
  "jourrapide.com",
  "rhyta.com",
  "superrito.com",
  "teleworm.us",
]);

export function esteEmailTemporar(email: string): boolean {
  const domeniu = email.trim().toLowerCase().split("@").pop() ?? "";
  return DOMENII_TEMPORARE.has(domeniu);
}
